name: Test

on:
  push:
    branches:
      - master
    paths:
      - 'meta.yml'

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Check if version changed
        id: version_check
        run: |
          git diff HEAD~1 HEAD -U0 | grep "+version"
      - name: Install hub
        if: success()
        run: |
          sudo apt install hub -y
      - name: Tag release
        run: |
          VERSION=$(git diff HEAD~1 HEAD -U0 -- meta.yml | grep "+version" | cut -d':' -f2 | tr -d '[:space:]')
          echo "Should tag v$VERSION"
          hub --help
