name: Test

on:
  push:
    branches:
      - master
    paths:
      - 'meta.yml'

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Run
        run: |
          ls -l
