name: Test

on:
  push:
    branches:
      - master
    paths:
      - 'meta.yml'

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Check if version changed
        run: |
          git diff HEAD~1 HEAD -U0 | grep "+version"
      - name: Tag release
        if: success()
        run: |
          echo "Should tag"
      - name: Third step
        run: |
          echo "This step?"
