name: Test

on:
  push:
    branches:
      - master
    paths:
      - 'meta.yml'

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Check if version changed
        id: version_check
        run: |
          git diff HEAD~1 HEAD -U0 | grep "+version"
      - name: Install hub
        if: success()
        run: |
          wget https://github.com/github/hub/releases/download/v2.12.3/hub-linux-amd64-2.12.3.tgz -O hub.tgz
          tar -xvf hub.tgz
          mv hub-linux-amd64-2.12.3/bin/hub .
      - name: Generate artifacts
        run: |
          mkdir artifacts
          echo "foo" > artifacts/foo
          echo "bar" > artifacts/bar
          echo "bar" > artifacts/baz
      - name: Tag release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USER: ikornaselur
        run: |
          VERSION="v$(git diff HEAD~1 HEAD -U0 -- meta.yml | grep '+version' | cut -d':' -f2 | tr -d '[:space:]')"
          ./hub release create -m "$VERSION" $VERSION
          for a in artifacts/*; do ./hub release edit -a $a $VERSION; done
