name: Test

on:
  push:
    branches:
      - master
    paths:
      - 'meta.yml'

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Check if version changed
        run: |
          git diff HEAD~1 HEAD -U0 | grep "+version"
      - name: Tag release
        if: success()
        run: |
          VERSION=$(git diff HEAD~1 HEAD -U0 -- meta.yml | grep "+version" | cut -d':' -f2 | tr -d '[:space:]') && \
          echo "Should tag v$VERSION"
      - name: Third step
        run: |
          echo "This step?"
